### ISSUE TITLE
AttributeError: Can't get attribute 'SPPF' on <module 'models.common' from '/home/zkx/graduation/Alpha-IoU/models/common.py'>

### ISSUE THREAD

**Issue by LoveYueForever** [Jacobi93/Alpha-IoU#4]
![image](https://user-images.githubusercontent.com/61404873/141429345-62c7f495-12f5-4584-a86b-1f65813762e7.png)
Thanks for your excellent project. When I test the trained model, I find this error. In the file models/common.py, I can't find the class SSPF. Could you please tell me the cause of this problem？ Thank you very much !

**Comment by LoveYueForever** [comment]
> ![image](https://user-images.githubusercontent.com/61404873/141429345-62c7f495-12f5-4584-a86b-1f65813762e7.png) Thanks for your excellent project. When I test the trained model, I find this error. In the file models/common.py, I can't find the class SSPF. Could you please tell me the cause of this problem？ Thank you very much !

Sorry， It's class SPPF

**Comment by NBStephens** [comment]
This is because YOLOv5 updated to v6.0 and the author has left the automatic download intact. See this issue on Yolov5 page (https://github.com/ultralytics/yolov5/issues/5175). 

You essentially have to wget  the v5.0 weights yourself (https://github.com/ultralytics/yolov5/releases/tag/v5.0) 

`wget https://github.com/ultralytics/yolov5/releases/download/v5.0/yolov5m.pt`

**Comment by Jacobi93** [comment]
@NBStephens Thx so much for your answer. This (ultralytics/yolov5#5175) should be exactly the same issue.
@LoveYueForever Thx so much for your interest in our repo. Actually, we use YOLOv5 in version 4.0 as mentioned in the README.md (version 5.0 may also be fine, but as discussed in ultralytics/yolov5#5175, version 6.0 is inconsistent with earlier versions (e.g., 4.0 and 5.0).

You should be able to run detect.py without bugs if you download our repo and use our uploaded weights (an example is shown below). If you wanna test other pre-trained models, plz remember to use some version earlier than version 6.0.
python detect.py --source inference/images --weights 'runs/train/voc_yolov5s_iou/weights/best.pt' --conf 0.25

It is a simple yet effective method so that you are welcome to apply our methods in other models and repos following the function 'bbox_alpha_iou' in [utils/loss.py](https://github.com/Jacobi93/Alpha-IoU/blob/main/utils/loss.py).

**Comment by LoveYueForever** [comment]
> This is because YOLOv5 updated to v6.0 and the author has left the automatic download intact. See this issue on Yolov5 page ([ultralytics/yolov5#5175](https://github.com/ultralytics/yolov5/issues/5175)).
> 
> You essentially have to wget the v5.0 weights yourself (https://github.com/ultralytics/yolov5/releases/tag/v5.0)
> 
> `wget https://github.com/ultralytics/yolov5/releases/download/v5.0/yolov5m.pt`

Thanks very much for answer.

**Comment by LoveYueForever** [comment]
> @NBStephens Thx so much for your answer. This ([ultralytics/yolov5#5175](https://github.com/ultralytics/yolov5/issues/5175)) should be exactly the same issue. @LoveYueForever Thx so much for your interest in our repo. Actually, we use YOLOv5 in version 4.0 as mentioned in the README.md (version 5.0 may also be fine, but as discussed in [ultralytics/yolov5#5175](https://github.com/ultralytics/yolov5/issues/5175), version 6.0 is inconsistent with earlier versions (e.g., 4.0 and 5.0).
> 
> You should be able to run detect.py without bugs if you download our repo and use our uploaded weights (an example is shown below). If you wanna test other pre-trained models, plz remember to use some version earlier than version 6.0. python detect.py --source inference/images --weights 'runs/train/voc_yolov5s_iou/weights/best.pt' --conf 0.25
> 
> It is a simple yet effective method so that you are welcome to apply our methods in other models and repos following the function 'bbox_alpha_iou' in [utils/loss.py](https://github.com/Jacobi93/Alpha-IoU/blob/main/utils/loss.py).

Thank you very much for your answer. The problem has been solved.
